config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
  resources :categories do
    resources :products
  end

  # get '/cart', to: 'cart#index'
  resources :order
  resources :cart
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :products
    belongs_to :order, optional: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :title, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_one :cart

    validates :address presence: true
    validates_format_of :address, :with => /^[a-zA-Z\d ]*$/i #only includes letters and numbers and spaces
    validates :total_price presence: true
    validates :shipping_time presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :users, through: :carts
    belongs_to :cart, optional: true
    belongs_to :category, optional: true

    validates :name, presence: true
    validates :price, presence: true
    validates :stock, length: {minimum: 0}
end

app/models/user.rb
class User < ApplicationRecord
  #Associations
  has_one :cart
  has_many :products
  has_many :orders
  has_many :items, through: :cart
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2, :github]
  #Devise

  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ["lower(username) = :value OR lower(email) = :value",
      { value: login.strip.downcase}]).first
  end

  def self.setup()
    Cart.create(user_id: (self.id))
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  #Omniauth
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,
            keys: [:username, :name, :email, :password, :password_confirmation])
        devise_parameter_sanitizer.permit(:sign_in,
            keys: [:login, :password, :password_confirmation])
        devise_parameter_sanitizer.permit(:account_update,
            keys: [:username, :name, :email, :password_confirmation, :current_password])
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def index
        
    end

    def create # current_user ? current_user.name : 'Rails Store'
        cart = Cart.find_or_create_by(user: current_user)
        product = Product.find(params[:product_id])
        item = Item.find_or_create_by(product: product, cart: cart)
        item.quanity ? item.update(quanity: (item.quanity + params[:quantiy].to_i)) : item.update(quanity: params[:quantiy])
        update_total_price()
        redirect_to cart_path(cart.id)
    end

    def show
        @cart = Cart.find_or_create_by(user: current_user)
        @items = Item.where(cart: @cart)
        render 'carts/show'
    end

    def update
        cart = Cart.find_or_create_by(user: current_user)
        product = Product.find(params[:product_id])
        item = Item.find_or_create_by(product: product, cart: cart)
        
        if item_params[:quanity].to_i < 1
            item.destroy
            update_total_price()
        else
            item.update(item_params)
            update_total_price()
        end

        redirect_to cart_path(cart.id)
    end

    private

    def item_params
        params.require(:item).permit(:quanity)
    end

    def update_total_price
        cart = Cart.find_or_create_by(user: current_user)
        items = Item.where(cart: cart)
        total = 0
        
        items.each do |i|
            total += (i.product.price.to_i * i.quanity.to_i)
        end

        cart.update(total_price: total.to_i)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    def new
        cart = Cart.find_or_create_by(user: current_user)
        @items = Item.where(cart: cart)
        render 'orders/new'
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @category = Category.find(params[:category_id])
        @products = @category.products.order(:price)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication
            set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
        else
            session["devise.github_data"] = request.env["omniauth.auth"]
            redirect_to '/'
        end
    end

    def google_oauth2
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication
            set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
        else
            session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
            redirect_to '/'
        end
    end

    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to '/'
        end
    end

    def failure
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages1!
        resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    end

    def devise_error_messages2!
        resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/show.html.erb
<div>
    <%# If logged in %>
    <% if current_user%>
        <div class="categories">
            <h1>Your Cart</h1>
            <% @items.each do |i| %>

                <%= form_for i, url: cart_path do |f| %>
                    <a id="category" class="list-group-item list-group-item-action"> <h4 id="product"> <%= i.product.name %> </h4>
                        <br>
                        <%= hidden_field_tag :product_id, i.product.id %>
                        <%= f.label "Quantity:"%>
                        <%= f.number_field :quanity %>
                        <%= f.label "Price (#{i.quanity}) : $ " %>
                        <%= f.label (i.product.price.to_i * i.quanity.to_i) %>
                        <%= f.submit "Update Cart" %>
                    </a>
                <% end %>

            <% end %>
            <h5> Total Price: $<%= @cart.total_price %> </h5>
            <h6 class="backwards"> <%= link_to "Check Out", new_order_path%> </h6>
            <h6 class="backwards"> <%= link_to "Back to Categories", '/categories'%> </h6>
        </div>
    <% end %>

    <%# If not logged in %>
    <% unless current_user %>
        <h1> <%= link_to "Please Login to View", '/'%> </h1>
    <% end %>
</div>

app/views/categories/index.html.erb
<div>
    <%# If logged in %>
    <% if current_user%>
        <div class="categories">
            <h1 class="title"> Categories </h1>
            
            <ul class="list-group">
                <% @categories. each do |c| %>
                    <a href="<%= category_products_path(c) %>" id="category" class="list-group-item list-group-item-action"> <h4 id="product"> <%= c.title %> </h4> </a>
                <% end %>
            </ul>
            <h6 class="backwards"> <%= link_to "Back to Login", '/'%> </h6>
        </div>
    <% end %>

    <%# If not logged in %>
    <% unless current_user %>
        <h1> <%= link_to "Please Login to View", '/'%> </h1>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
    <nav class="navbar navbar-expand-lg bg-light">
      <a class="navbar-brand" href=""> <%= current_user ? current_user.name : 'Rails Store' %> </a>
      <div>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/categories">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/cart/<%= current_user ? current_user.id : '#' %>">Cart</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
          </li>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<div>
    <%# If logged in %>
    <% if current_user%>
        <div class="categories">
            <h1>Make a Order</h1>
            <% @items. each do |i| %>
                    <a id="category" class="list-group-item list-group-item-action">
                    <h4 id="product"> 
                        <%= i.product.name %>
                        <%= "(x#{i.quanity})" %>
                        <br>
                        <%= "$#{i.product.price}" %>
                    </h4>
                    </a>
                <% end %>
            <h6 class="backwards"> <%= link_to "Place Order", order_path%> </h6>
            <h6 class="backwards"> <%= link_to "Back to Cart", cart_path%> </h6>
        </div>
    <% end %>

    <%# If not logged in %>
    <% unless current_user %>
        <h1> <%= link_to "Please Login to View", '/'%> </h1>
    <% end %>
</div>

app/views/pages/home.html.erb
<div>
    <form class="form-signin">
        <%# Shopping Cart Icon  %>
        <img class="mb-4" src="https://img.icons8.com/dotty/80/000000/shopping-cart.png" width="80" height="80">
        <h1 class="h3 mb-3 font-weight-normal"> <u>Welcome to the Store</u></h1>

        <%# If logged in %>
        <% if current_user%>
            <div class="container">
            <h1 class="h4 mb-3 font-weight-normal"> <%= image_tag(current_user.image) unless current_user.image.nil? %> <%= current_user.name %> </h1>
            </div>
        <% end %>

        <%# If not logged in %>
        <% unless current_user %>
            <h2 class="h5 mb-3 font-weight-normal"> <img src="https://img.icons8.com/ios/50/000000/facebook--v1.png" width ="40" height="40"/> <%= link_to "Sign/Up in with Facebook", user_facebook_omniauth_authorize_path %> </h2>
            <h2 class="h5 mb-3 font-weight-normal"> <img src="https://img.icons8.com/wired/64/000000/github.png" width="40" height="40"/> <%= link_to "Sign/Up in with Github", user_github_omniauth_authorize_path %> </h2>
            <h2 class="h5 mb-3 font-weight-normal"> <img src="https://img.icons8.com/carbon-copy/100/000000/google-logo.png" width="40" height="40"/> <%= link_to "Sign/Up in with Google", user_google_oauth2_omniauth_authorize_path %> </h2>
            <h2 class="h5 mb-3 font-weight-normal"> <img src="https://img.icons8.com/ios/50/000000/email-open.png" width="40" height="40"/> <%= link_to "Sign Up With Email", new_user_registration_path %> </h2>
            <h2 class="h5 mb-3 font-weight-normal"> <img src="https://img.icons8.com/ios/50/000000/email-open.png" width="40" height="40"/> <%= link_to "Login With Email", new_user_session_path %> </h2>
            <!-- additional fields  -->
        <% else %>
            <h3 class="h4 mb-3 font-weight-normal"> <%= link_to "Proceed",  categories_path%> </h3>
            <h3 class="h6 mb-3 font-weight-normal"> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </h3>
        <% end %>
    </form>
</div>

app/views/products/index.html.erb
<div>
    <%# If logged in %>
    <% if current_user%>
        <div class="categories">
            <h1 class="title"> <%= @category.title %> </h1>
            
            <ul class="list-group">
                <% @products. each do |product| %>
                    <a id="products" class="list-group-item list-group-item-action"> <h4 id="product"> <%= product.name %> </h4> <%= number_to_currency product.price%> </a>

                    <%= form_tag cart_index_path do %>
                        <%= hidden_field_tag :product_id, product.id %>
                        <%= number_field_tag :quantiy, 1 %>
                        <%= submit_tag "Add to Cart" %>
                    <% end %>

                <% end %>
            </ul>
            <h6 class="backwards"> <%= link_to "Back to Categories", '/categories'%> </h6>
        </div>
    <% end %>

    <%# If not logged in %>
    <% unless current_user %>
        <h1> <%= link_to "Please Login to View", '/'%> </h1>
    <% end %>
</div>